export default {
  HEAD: 'Typical technology stack',
  JS: 'JavaScript',
  REACT: 'React',
  REACT_NATIVE: 'React Native',
  VUEJS: 'VueJS',
  APOLLO: 'Apollo Client',
  REDUX: 'Redux',
  STYLE_COMPONENTS: 'Style Components',
  CSS: 'CSS',
  SASS: 'Sass',
  HTML: 'HTML',
  GIT: 'Git',
  FIREBASE: 'Firebase',
  WEBPACK: 'Webpack',
  SENTRY: 'Sentry',
};
